### ISSUE TITLE
no Go files in server directory

### ISSUE THREAD

**Issue by garyrob** [tlsnotary/server#1]
I installed the go compiler and did the steps at https://github.com/tlsnotary/server. But when I got to the line:

`go build -o notary`

the output was

`no Go files in /my/path/to/server`

Of course, there is a notary.go file in server/src, but at this point, following the instructions, I am in the server dir. I've never used Go and I don't know whether it automatically looks in src, but in this case, that doesn't seem to be happening.

**Comment by themighty1** [comment]
Thanks, fixed the issue in the README.
